[general]
import = ["~/.config/alacritty/themes/themes/one_dark.toml"]

[window]
padding = { x = 5, y = 5 }
opacity = 0.75

[font]
normal = { family = "HackGen35 Console NF", style = "Regular" }
size = 9

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }

[terminal]
shell = "/bin/fish"

[mouse]
hide_when_typing = true
