return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter.configs").setup({
			ensure_installed = {
				"bash",
				"css",
				"csv",
				"desktop",
				"dockerfile",
				"fish",
				"git_config",
				"gitattributes",
				"gitignore",
				"go",
				"gomod",
				"gosum",
				"gotmpl",
				"gowork",
				"graphql",
				"html",
				"ini",
				"javascript",
				"jq",
				"kdl",
				"lua",
				"make",
				"nginx",
				"proto",
				"rust",
				"sql",
				"ssh_config",
				"toml",
				"tsx",
				"typescript",
				"typespec",
				"yaml",
			},
			sync_install = false,
			highlight = { enable = true },
			indent = { enable = true },
		})
	end,
}
