# prefix key
set -g prefix C-f
unbind C-b

# Reload config file
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; display "Reloaded config file"

# split pains
bind \\ split-window -h
bind - split-window -v

# pane navigation
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# maximize pane
bind -n C-z resize-pane -Z

# window navigation
bind -n C-left previous-window
bind -n C-right next-window

# status bar
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'
setw -g status-style bg=colour123,fg=colour232
set -g status-left ""
set -g status-right ""
set -g base-index 1
setw -g window-status-current-format '#[bg=colour147,fg=colour232]#{?client_prefix,#[bg=colour3],} #I #W '
setw -g window-status-format '#[fg=colour242] #I #W '

set-option -g mouse on

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '$XDG_DATA_HOME/tmux/plugins/tpm/tpm'

