[tools]
"cargo:cargo-expand" = "latest"
golangci-lint = "latest"
node = "24"
"npm:@aikidosec/safe-chain" = "1.5.14"
"npm:ccusage" = "latest"
"npm:cz-git" = "latest"
"npm:czg" = "latest"
"npm:difit" = "latest"
pnpm = "11"
